/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xqd_myapplication_Java2CJNI */

#ifndef _Included_com_xqd_myapplication_Java2CJNI
#define _Included_com_xqd_myapplication_Java2CJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xqd_myapplication_Java2CJNI
 * Method:    java2c
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_xqd_myapplication_Java2CJNI_java2c
  (JNIEnv *, jobject);

/*
 * Class:     com_xqd_myapplication_Java2CJNI
 * Method:    getPassword
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_xqd_myapplication_Java2CJNI_getPassword
  (JNIEnv *, jobject);

JNIEXPORT jstring JNICALL Java_com_xqd_myapplication_Java2CJNI_getName
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
