/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Java2CJNI */

#ifndef _Included_Java2CJNI
#define _Included_Java2CJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Java2CJNI
 * Method:    java2c
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Java2CJNI_java2c
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
